name: 'coverage'
on:
    pull_request:
        branches:
            - develop
            - test_*_branch
jobs:
    coverage:
        permissions:
          checks: write
          pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                coverage-file: ./cov/report.json
                base-coverage-file: ./cov/develop/report.json
			  	
