name: Coverage

on:
  pull_request:
    branches:
      - develop
      - test_*_branch

jobs:
  Coverage:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        coverage-file: ./coverage/report.json
        base-coverage-file: ./coverage/develop/report.json
			  	
