name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: actions/checkout

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm run test -- --watchAll=false
