name: GitHub Actions Demo

on: 
  push:
    branches:
      - "test_*_branch"
      - "develop"

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # - name: set nodejs version
      #   uses: actions/setup-node@v3
      #   with: 
      #     node-version: 14
      #     cache: npm

      - name: echo node version
        run: node -v

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm run test -- --watchAll=false
